# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Larry
tagline:          'Blog'
description:      'Larry lus programming blog'
url:              http://larry850806.github.io
baseurl:          /

author:
  name:           'Larry Lu'
  url:            https://facebook.com/Larry850806

paginate:         5

# Custom vars
version:          2.1.0
future: true

github:
  repo:           https://github.com/Larry850806/larry850806.github.io
gems: [jekyll-paginate, jekyll-gist]
